### ISSUE TITLE
Consensus testing of minscripts

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-miniscript#124]
#123 brought an interesting point that we should consensus test our miniscript with rust-libbitcoinconsensus. 

Create transactions using rust-miniscripts and check the transaction validity/satisfaction logic/weight calculation etc and other features with https://github.com/rust-bitcoin/rust-bitcoinconsensus. We can also grammar that Pieter had to generate random miniscirpts. 

Not completely sure of how we are going to do this, but I think we should have this.

**Comment by dgpv** [comment]
I've generated some sample satisfied,valid,nonmalleable miniscript instances (in the form of graphs in .dot format, exported from Alloy analyzer), they are at  https://github.com/dgpv/miniscript-alloy-spec/tree/master/generated_data

The .dot files can be processed with this script: https://github.com/dgpv/miniscript-alloy-spec/blob/master/tools/parse_miniscript_dot.py
It outputs the same output as C++ miniscript binary and ignores witnesses, but the script can be extended to extract witness data from the .dot files (the witnesses are modelled as: EmptySig, ValidSig, CorrectPreimage, WrongPreimage, WitOne, WitZero, PubKey, DummyWitness)

In total there are 8001 sample, but the presence of different fragments are not uniform. Most of the samples contain 'multi' fragment, and only 103 contain "thresh" fragment, for some reason. This might be an artifact of how Alloy analyzer searches for samples, or the result of the interaction of the properties of the fragments themselves, or both.

**Comment by sanket1729** [comment]
This is really cool. I just tested out the script and it outputs in a format that I can directly use for testing of rust-miniscript.

**Comment by dgpv** [comment]
Note that there's duplicate samples even when you take witness data into account. Alloy marks different instances with numbers, like Multi0, Multi1, etc, and then samples can differ at which position in Or_d.args, for exampple which concrete instance resides. For example, 4587.dot 4814.dot have identical rendering into the picture, but the .dot file differs. I think I will filter these files based on rendering

**Comment by dgpv** [comment]
I've filtered out the sample files that gave identical rendering in graphvis. I've created a separate repo for generated data:https://github.com/dgpv/miniscript-alloy-spec-generated-samples, newly filtered data is there now.

There still can be some "duplicates" in a sense - there could be two samples that differ by the witnesses in the ignored part of the script. These witnesses are not relevant for satisfaction, and such samples would be identical for the testing purposes. But I decided to not filter them out at this time.

**Comment by dgpv** [comment]
The samples only contain 'sha256' for hash and 'after' for timelock. Other hash and timelock fragments are equivalent to these in terms of structure of the script, so the sample generation explicitly disabled other fragments. If you want to test with 'hash160', for example, you could just substitute some sha256 with hash160 in some existing sample.

**Comment by dgpv** [comment]
I've added the ability to render script to `tools/parse_miniscript_dot.py`:

```
$ tools/parse_miniscript_dot.py ~/miniscript-alloy-spec-generated-samples/8ed9d5a6d084d70e607eb4fb8801ba86d481eb6c/1005.dot 
type=B safe=yes nonmal=yes dissat=unknown input=- output=1 miniscript=and_b(or_d(multi(2,A,B,C),after(500000001)),a:multi(2,D,E,F))
script: 2 <A> <B> <C> 3 OP_CHECKMULTISIG OP_IFDUP OP_NOTIF <0165cd1d> OP_CHECKLOCKTIMEVERIFY OP_ENDIF OP_TOALTSTACK 2 <D> <E> <F> 3 OP_CHECKMULTISIG OP_FROMALTSTACK OP_BOOLAND
```

Might help with testing of compilation from miniscript to script

**Comment by dgpv** [comment]
Witnesses can also be extracted from .dot file the same way as script is extracted. But because the optimal satisfaction is a hyperproperty (the best instance might need to be chosen between several valid satisfaction), it cannot be directly modelled with Alloy. Therefore the witness conviguration in the .dot files is just some valid witness, but not necessary what optimal solver would produce. I guess extracting witnesses would not be very useful to test the implementation. It may be useful to test the spec, though, by executing the script with the extracted witnesses and checking that the script was successfully satisfied.

**Comment by dgpv** [comment]
I've added the ability to render witness to `tools/parse_miniscript_dot.py`, just in case, even if witness in .dot files may not be optimal.

**Comment by dgpv** [comment]
The formal spec (with what the current batch of samples linked in the previous messages was generated) were needlessly restrictive: it stated that 'non-malleability' property holds for all nodes, while it is only necessary that this property holds for the root node. This was fixed in https://github.com/dgpv/miniscript-alloy-spec/commit/3aa214f391a130c6a77e72afcce798a9e78690ed and I will generate another set of samples, with fixed spec.

**Comment by dgpv** [comment]
The distinction in the previous message ("'non-malleability property holds for all nodes, while it is only necessary that this property holds for the root node.") is not relevant when we consider non-malleable samples, because 'non-malleability holds for root node' implies 'non-malleability holds for all nodes'. The distinction only relevant when we are generating malleable samples ("nonmal=no"). This means that the initial samples at https://github.com/dgpv/miniscript-alloy-spec-generated-samples/blob/master/8ed9d5a6d084d70e607eb4fb8801ba86d481eb6c.zip are fine. I will generate the malleable samples, too, but the first (non-malleable) samples are OK.

**Comment by dgpv** [comment]
I've added malleable samples to the "generated samples" repo: https://github.com/dgpv/miniscript-alloy-spec-generated-samples/blob/master/33b85f29d53e2623b955d55afe9061f5d0fc96d3_malleable.zip
The archive contains 7024 .dot files, that are generated using "main" run clause of the spec, but with main_search_predicate modified to say `RootNode not in NonMalleableHolds`. This means that all samples represent scripts that do not have non-malleable property.

**Comment by sanket1729** [comment]
Resuming work on this, now that we have rust-bitcoin 0.26.
