### ISSUE TITLE
timelock checks

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-miniscript#421]
I am unable to understand this bit of code (from `miniscript/types/extra_props.rs`)
```rust
            Terminal::After(t) => {
                // Note that for CLTV this is a limitation not of Bitcoin but Miniscript. The
                // number on the stack would be a 5 bytes signed integer but Miniscript's B type
                // only consumes 4 bytes from the stack.
                if t == 0 || (t & SEQUENCE_LOCKTIME_DISABLE_FLAG) != 0 {
                    return Err(Error {
                        fragment: fragment.clone(),
                        error: ErrorKind::InvalidTime,
                    });
                }
                Ok(Self::from_after(t))
            }
```
Here `t` is a `u32` that is the nLockTime, for nLockTime all values are valid, so my questions are:

1. Why do we check that `t` is not zero?
2. Why we check that the top bit is set?
3. If the comment is correct, why would the number on the stack be 5 bytes?

**Comment by apoelstra** [comment]
1. Because a 0-valued timelock serves no purpose (it is equivalent to `v:1`), and the Miniscript type system requires that the timelock fragment leave a non-zero value on the stack. Since the fragment leaves the timelock value on the stack, to get the typing system to work we have to forbid setting this value to zero.
2. I'm not sure if this is a bug (it looks like it was copied from the nSequence handling code, and [BIP 65](https://github.com/bitcoin/bips/blob/master/bip-0065.mediawiki) makes no mention of magic bits) or if it's a hacky way to make 5-byte numbers illegal as the comment suggests. @sanket1729 ?
3. The reason we don't allow 5-byte "numbers" is that Script's numerical opcodes, including `BOOLAND` and `BOOLOR`, don't treat them as numbers and will not accept them. Miniscript's type system requires that the output of the timelock fragment be a valid number, and since the output is the user-provided timelock, we need to forbid the user from providing a 5-byte value.

**Comment by sanket1729** [comment]
I believe that 1) and 3) are correctly addressed by Andrew. And you made a significant contribution pushing making reasoning about the 2) easier.
