### ISSUE TITLE
`rust-analyzer` chokes on this repo

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-miniscript#509]
Often when I'm working on this repo my `rust-analyzer` chokes (all 4 cores max out), does anyone else hit this issue?

**Comment by apoelstra** [comment]
I can't tell if it's maxing out cores but yeah, it seems like ALE is not working for me on this repo. At least, not at a reasonable speed.

**Comment by tcharding** [comment]
Cool, so its not just me. I'll post if I find anything. Thanks.

**Comment by sanket1729** [comment]
Yeah, it takes a while for me(30 sec) the first time I load it. But works fine afterwards

**Comment by sanket1729** [comment]
I had a theory that this happens because the compile time of rust-miniscript is high as we have a lot of monomorphisation going on. I was hoping we could somehow split the make the compilation units smaller by splitting functions into smaller generic functions and non-generic functions.  Something that std library does to reduce compile times. For example, 

```
pub fn read<P: AsRef<Path>>(path: P) -> io::Result<Vec<u8>> {
    fn inner(path: &Path) -> io::Result<Vec<u8>> {
        let mut file = File::open(path)?;
        let size = file.metadata().map(|m| m.len() as usize).ok();
        let mut bytes = Vec::with_capacity(size.unwrap_or(0));
        io::default_read_to_end(&mut file, &mut bytes, size)?;
        Ok(bytes)
    }
    inner(path.as_ref())
}
```
In the above, inner is only compiled once. 

However, most of our functions are not as easy as our datastructures are dependent on `Terminal<Pk>` or `Miniscript<Pk>`. Cannot apply similar tricks to these APIs.
