### ISSUE TITLE
update to bitcoin 0.31.0 and make a new release

### ISSUE THREAD

**Issue by benma** [rust-bitcoin/rust-miniscript#622]
Would be nice to keep all the rust-* crates in sync with each other in terms of releases so that downstream projects can make use of the newest releases.

**Comment by tcharding** [comment]
Thanks for raising the issue and for noticing we did a new release! This upgrade is held up by the `bitcoind-tests` crate needing to update `bitcoind` and `bitcoincore-rpc`.

All of which are my fault because early during the RC cycle I just deleted `bitcoind-tests` locally and promptly forgot about it.

- https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/311

**Comment by tcharding** [comment]
Oh perhaps we can just use old versions of `bitcoind` and `bitcoincore-rcp` in `bitcoind-tests` temporarily, @sanket1729 and/or @apoelstra would you be ok with that? (Just an idea, I haven't checked it works yet.) And do an RC of miniscript that folk can get on and use?

**Comment by apoelstra** [comment]
@tcharding I'm fine with it, but it's likely not to work because `bitcoind` and `bitcoincore-rpc` depend on an old version of `bitcoin`.

But maybe you can hack around any incompatibilities by e.g. serializing objects of one version and deserializing as objects of another.

**Comment by tcharding** [comment]
I think we [0] should just take this as a painful lesson and in future we should have the `rust-bitcoincore-rcp` release ready to drop the same time as `rust-bitcoin`.

[0]  (mainly me, because I deleted `bitcoind-tests/` out of `rust-miniscript` a few weeks ago while testing RCs)

**Comment by apoelstra** [comment]
There was a very long time when the `rust-bitcoincore-rpc` maintainer was absent (which is why there are a ton of PRs where I was doing review even though I don't use or maintain the crate). If we gate rust-bitcoin releases on it we'll regret it.

Though in this case, yeah, we probably could've done it.

In the past we've hacked around this. I don't think it's a problem to hack around it again. This is originally why our RPC-using test stuff is in a separate crate like this.

**Comment by tcharding** [comment]
cc https://github.com/rust-bitcoin/rust-bitcoin/discussions/2199

**Comment by benma** [comment]
This new 11.0.0 release depends on bech32-0.10.0-beta, which is marked as unstable on https://docs.rs/bech32/0.10.0-beta/bech32/. Is that a problem? Could bech32 get a new stable release too, or can I rely on the beta as-is?

**Comment by apoelstra** [comment]
@benma you can rely on the beta as-is. But in future we'll keep in mind that docs.rs marks beta crates in a scary/annoying way like this.
