### ISSUE TITLE
CheckSequenceVerify with OP_DROP

### ISSUE THREAD

**Issue by louisinger** [rust-bitcoin/rust-miniscript#776]
According to the following issue: https://github.com/rust-bitcoin/rust-miniscript/issues/548, `OP_DROP` is never used in miniscript. 

However, most of the scripts using `OP_CSV` are using `OP_DROP` to clean the stack after the verification. Instead, miniscript descriptor compiles to `OP_CSV OP_VERIFY`. This is not common, [BIP112](https://bips.dev/112/) itself never mention `OP_VERIFY` and it makes several onchain scripts not parsable by miniscript.

What's the idea of using OP_VERIFY after CSV ? Isn't useless to OP_VERIFY the input locktime ? It should never fail ?
Also, is there a way to compile `older` descriptor to `CSV DROP` script ?

**Comment by apoelstra** [comment]
It's definitely not a goal of Miniscript to support parsing all on-chain scripts. However, I do have a goal to write some sort of "extended Miniscript parser" that can interpret things like CSV with DROP (and skip pushes followed by DROPs, can evaluate fixed arithmetic fragments, etc) and convert them to the equivalent Miniscript fragments, to allow them to be analyzed and interpreted.

But that project would be separate from Miniscript (even if I put it into this library), and also I've never started it. Despite talking about it for many years.

As for the historical question of why we used VERIFY instead of DROP ... let me search my IRC logs. I believe it was as simple as "we wanted to minimize the total number of opcodes we were using" because that made our parser conceptually smaller, and if we one day attempted some sort of formal modelling of all the opcodes used by Miniscript, this would be one fewer do deal with.

**Comment by apoelstra** [comment]
Ah, no, there is a better reason than this.

If you look at https://bitcoin.sipa.be/miniscript/ you will see that there is no "<n> CSV VERIFY" fragment. There is a "<n> CSV" fragment and there is a "<fragment> VERIFY" fragment, and together those provide the same functionality as "<n> CSV DROP", without needing to define a whole extra fragment.

Minimizing the total number of *fragments* is definitely a design goal of Miniscript, because every fragment needs to be hand-verified to be exactly correct and satisfy exactly the properties that we claim for it. So extra fragments are opportunities for mistakes in the language design, and mistakes in the design can easily turn into critical money-losing bugs in users' code.

**Comment by louisinger** [comment]
> Minimizing the total number of fragments is definitely a design goal of Miniscript, because every fragment needs to be hand-verified to be exactly correct and satisfy exactly the properties that we claim for it. So extra fragments are opportunities for mistakes in the language design, and mistakes in the design can easily turn into critical money-losing bugs in users' code. 

I totally understand this, but practically It seems to me that most HTLC-like scripts are implemented with `CSV DROP`. So this design makes impossible potential migration to miniscript in a lot of cases. I don't realize the implications and the work needed to add a new DROP fragment but maybe the pain is worth the gain ? 

anyway, I get the point and I have an answer, thanks, let's close the issue if out of scope

**Comment by apoelstra** [comment]
Sounds good, will close.

Compatibility with existing scripts was never a goal -- and indeed, it's not just the use of CSV DROP that makes us incompatible with HTLCs. There is also the fact that HTLCs use a branch to interpret an object either as a public key or a hash preimage, something which Miniscript can't express.
